### ISSUE TITLE
Problem: email address in normalization report is not configurable

### ISSUE THREAD

**Issue by jhsimpson** [JiscRDSS/rdss-archivematica#110]
To reproduce this issue: set `ARCHIVEMATICA_DASHBOARD_EMAIL_DEFAULT_FROM_EMAIL` to value `noreply@researchdata.alpha.jisc.ac.uk` as a parameter to the Dashboard. When it tries to send an email, the result is:
```MessageRejected: An error occurred (MessageRejected) when calling the SendRawEmail operation: Email address is not verified. The following identities failed the check in region EU-WEST-1: Archivematica <ArchivematicaSystem@archivematica.org>
```

The normalize report is ignoring `ARCHIVEMATICA_DASHBOARD_EMAIL_DEFAULT_FROM_EMAIL`.

The hardcoded value here https://github.com/JiscRDSS/archivematica/blob/qa/jisc/src/MCPClient/lib/clientScripts/normalizeReport.py#L158
needs to get replaced by the value of the environment variable  `ARCHIVEMATICA_DASHBOARD_EMAIL_DEFAULT_FROM_EMAIL`

**Comment by sevein** [comment]
Off the top of my head:
- SS: AIP removal request
- MCPClient: emailFileReport, normalizationReport
