### ISSUE TITLE
Problem: Makefile does not use git tags

### ISSUE THREAD

**Issue by jhsimpson** [JiscRDSS/rdss-archivematica#114]
The Makefile in this repo is used when building the images used to deploy the jisc-qa.archivematica.org environment.  The Makefile currently checks out the head of each repo it is building images from.

In production environments, images are built using `publish-images-playbook.yml`. All the images checkout the git repositories using semver tags. 

The Makefile should reference the same git tags as the ansible publish playbook, to make sure the qa environment is deployed with the correct versions of each component (i.e. the versions intended to be deployed in production).

**Comment by sevein** [comment]
@jhsimpson this is now fixed in #115. The new `make clone` relies on the Ansible playbook so we won't need to do it manually. This is not included in rdss-archivematica v0.2.0 where it's probably better to run something like the following:

```bash
git fetch
git reset --hard v0.2.0

PROJECTS=(
    "./src/archivematica:v0.1.1"
    "./src/archivematica-storage-service:v0.2.0"
    "./src/rdss-archivematica-automation-tools:v0.1.1"
    "./src/rdss-archivematica-channel-adapter:v0.2.6"
    "./src/rdss-arkivum-nextcloud:v0.1.0"
    "./src/rdss-archivematica-msgcreator:v0.1.0-rc.1"
)

for project in "${PROJECTS[@]}" ; do
    dir="${project%%:*}"
    version="${project##*:}"

    ( cd $dir && git fetch && git reset --hard $version )
done
```
