### ISSUE TITLE
Problem: New pipeline create after upgrade

### ISSUE THREAD

**Issue by mamedin** [JiscRDSS/rdss-archivematica#134]
Problem: New pipeline create after upgrade.

After a QA env upgrade running (from 0.2.0-rc2 to 0.3.0_rc1):

```
DOMAIN_NAME=jisc-qa.archivematica.org make all ENV=qa SHIBBOLETH_CONFIG=archivematica NEXTCLOUD_ENABLED=true
```

The bootstrap process creates a new pipeline everytime it is run this `make all` command.

**Comment by joel-simpson** [comment]
The fix for this issue (JiscRDSS/archivematica#55) was merged to archivematica v0.5.0 which was included in rdss-archivematica 0.5.1
