### ISSUE TITLE
Problem: new release of Channel Adapter required for v0.7.0

### ISSUE THREAD

**Issue by joel-simpson** [JiscRDSS/rdss-archivematica#226]
The channel adapter is being updated to support the new asynchronous API endpoint, described here: 
https://github.com/JiscRDSS/rdss-archivematica-channel-adapter/issues/104
The PR for this issue needs to be merged before we can update the rdss-archivematica playbook and cut the first 0.7 release candidate.

**Comment by mjaddis** [comment]
we've already cut several 070 rcs so am closing this issue
