### ISSUE TITLE
Problem: async transfers from channel adapter need configuration

### ISSUE THREAD

**Issue by sevein** [JiscRDSS/rdss-archivematica#228]
[RDSSARK-479](https://jiscdev.atlassian.net/browse/RDSSARK-479)

We've done work on two ends:
- https://github.com/JiscRDSS/rdss-archivematica-channel-adapter/pull/90 which updates the channel adapter so it speaks the new Package API and downloads the datasets directly into a transfer source location.
- https://github.com/artefactual/archivematica/pull/1211 which updates the Package API so it can accept `path` values in the request where the UUID component pointing to the transfer source location is not indicated - it will use the default location for the `TS` purpose instead.

There's need for some integration work in this repository:

- Create a new transfer source location (e.g. `/home/adapter`) - see `rdss-create-storage-locations.py`, make sure that it's the default TS location in Storage Service.
- Add volume `archivematica_storage_service_location_data:/home:rw` to `rdss-archivematica-channel-adapter-consumer` so the adapter can write.
- Set `RDSS_ARCHIVEMATICA_ADAPTER_AMCLIENT.TRANSFER_DIR` to `/home/adapter` in the `rdss-archivematica-channel-adapter-consumer` service.

**Comment by mamedin** [comment]
PR #230 fixes the issue except for setting this new TS as default.
