### ISSUE TITLE
Channel adapter throws resource not found issue

### ISSUE THREAD

**Issue by murali-arkivum** [JiscRDSS/rdss-archivematica#241]
When Jisc sends v3.0.1 to messages to 280-dev environment, below error occurs
time="2018-08-17T11:23:55Z" level=error msg="Error trying to persist the research object: ResourceNotFoundException: Requested resource not found\n\tstatus code: 400, request id: EBBAKPEQS04S2EL525J2CSED5JVV4KQNSO5AEMVJF66Q9ASUAAJG" cmd=consumer version=v0.7.0-rc.3

**Comment by murali-arkivum** [comment]
root cause is because of missing dynamodb tables

**Comment by mjaddis** [comment]
This is now fixed.  Closing issue.
