### ISSUE TITLE
Problem: we don't have a release yet

### ISSUE THREAD

**Issue by sevein** [JiscRDSS/rdss-archivematica#30]
We should pin dependencies in this repo (ref `qa/jisc` not enough) and publish a tag `MVP` which probably requires tags down in the hierarchy.

When someone is deploying he would start choosing the tag we've created, e.g.:

    $ git clone -b MVP https://github.com/JiscRDSS/rdss-archivematica

**Comment by sevein** [comment]
Thoughts?

**Comment by sevein** [comment]
#### Use of canonical fields and checksums
- https://github.com/JiscRDSS/rdss-archivematica-channel-adapter/pull/25
- https://github.com/JiscRDSS/archivematica/pull/24

#### Automated workflow: default AIP storage location
- https://github.com/JiscRDSS/archivematica/pull/22
- https://github.com/JiscRDSS/archivematica-storage-service/pull/8

#### rdss-archivematica
- https://github.com/JiscRDSS/rdss-archivematica/pull/29
- Richard's https://github.com/JiscRDSS/rdss-archivematica/pull/26
- Richard's https://github.com/JiscRDSS/rdss-archivematica/pull/28

**Comment by sevein** [comment]
Sounds like we're good to go?

**Comment by sevein** [comment]
[MVP milestone](https://github.com/search?utf8=%E2%9C%93&q=user%3AJiscRDSS+milestone%3A%22MVP%22+is%3Aopen+fork%3Atrue+sort%3Acreated-desc&type=Issues) under JiscRDSS organization.

**Comment by jhsimpson** [comment]
yes this looks resolved.
