### ISSUE TITLE
Problem: Compose uses dynamic ports

### ISSUE THREAD

**Issue by sevein** [JiscRDSS/rdss-archivematica#31]
Update our services in `docker-compose.dev.yml` with fixed ports in the host, it's not convenient having to look up the ports all the time you start a new environment, restart a service, recreate a container, etc...

**Comment by lower29** [comment]
The `am-shib` container for `nginx` already overrides this to use 443 and 8443. Are these appropriate for non-Shib too?

**Comment by sevein** [comment]
Just going to change `minio` and `msgcreator` for now but good idea.
