### ISSUE TITLE
Problem: Characterization job fails 

### ISSUE THREAD

**Issue by joel-simpson** [JiscRDSS/rdss-archivematica#37]
"Job Characterize and extract metadata" fails in the current QA environment 
https://archivematica.jisc-qa.archivematica.org
This appears to have occured in all transfers created since the latest environment build. 
The Standard Error output includes: 

```
edu.harvard.hul.ois.fits.exceptions.FitsConfigurationException: /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/Joel_first_qa_test-1582e248-0628-4ed8-8b7e-0a9b3f3a535f/objects/woodpigeon-pic.jpg does not exist or is not readable
```

**Comment by sevein** [comment]
Hopefully fixed here: https://github.com/JiscRDSS/archivematica/pull/27. We need to test.

**Comment by joel-simpson** [comment]
I have tested this in the demo-jisc environment with two datasets, in both cases characterization passed as expected. Closing issue as fixed.
