### ISSUE TITLE
Problem: Format Identification with Fido Fails

### ISSUE THREAD

**Issue by joel-simpson** [JiscRDSS/rdss-archivematica#39]
Testing for the "interactive" workflow in the Jisc-qa environment. Using the OfficeDocs directory from SampleTransfers to create a test transfer.   When presented with the decision point for the job "identify file format", I select Fido as the tool to use. 

The job then fails, with the following standard error output: 
Fido exited 1 and no format was found.
stdout: 

stderr: Traceback (most recent call last):
  File "/usr/local/bin/fido", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/fido/fido.py", line 839, in main
    fido.load_fido_xml(file)
  File "/usr/local/lib/python2.7/dist-packages/fido/fido.py", line 254, in load_fido_xml
    tree = ET.parse(file)
  File "<string>", line 62, in parse
  File "<string>", line 26, in parse
IOError: [Errno 2] No such file or directory: '/usr/lib/archivematica/archivematicaCommon/externals/fido/archivematica_format_extensions.xml'

Error: IDCommand with UUID a8e45bc1-eb35-4545-885c-dd552f1fde9a exited non-zero.

**Comment by lower29** [comment]
Can this issue be closed now?

**Comment by joel-simpson** [comment]
Yes, this issue was fixed with https://github.com/JiscRDSS/archivematica/pull/31 which has now been merged.
