### ISSUE TITLE
Transfer created with msgCreator is not automatically approved

### ISSUE THREAD

**Issue by joel-simpson** [JiscRDSS/rdss-archivematica#47]
Testing in the https://archivematica.demo-jisc.archivematica.org/ environment.
I sent a message with msgCreator using the json for SIP1 from here: https://github.com/artefactual-labs/rdss-archivematica-test-data-corpus/blob/master/collection/10.5281/zenodo.46430/SIPmetadata/SIP-1.request.json

msgCreator confirmed the message was sent: 
Message sent! 
ShardId: shardId-000000000002 
SequenceNumber: 49574538886713461413187707159719502317916661466003406882

The dataset shows up in the Transfer tab - but is awaiting manual approval. Have waited for an hour but transfer is still showing that is "awaiting decision".

**Comment by joel-simpson** [comment]
@mamedin looked at the logs and found potential issues with Mysql. 

```
DEBUG     2017-06-27 17:40:48  archivematica.mcp.server:jobChain:__init__:73:  Chain: MicroServiceChain ID: fffd5342-2337-463f-857a-b2c8c3778c6d; Transfers In progress
INFO      2017-06-27 17:40:48  archivematica.mcp.server:jobChainLink:__init__:91:  Running Approve standard transfer (unit 69819795-bee4-4b9d-a36a-e98fd2320a99)
INFO      2017-06-27 17:40:48  archivematica.mcp.server:linkTaskManagerChoice:checkForPreconfiguredXML:122:  Using preconfigured choice None for 0c94e6b5-4714-4bec-82c8-e187e0c04d77
DEBUG     2017-06-27 17:40:54  archivematica.mcp.server.rpcserver:RPCServer:approveJob:54:  Approving: c80ee97b-eb1b-4518-ab32-46ffac1c2380 6953950b-c101-4f4c-a0c3-0cd0684afe5e 1
ERROR     2017-06-27 17:40:54  sqlalchemy.pool.QueuePool:pool:_finalize_fairy:696:  Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 829, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 83, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
```
He restarted the mysql container, and the next transfer I created was automatically approved.

**Comment by mamedin** [comment]
The mcp-server log shows a mysql problem:

`DEBUG     2017-06-27 17:40:48  archivematica.mcp.server:jobChain:__init__:73:  Chain: MicroServiceChain ID: fffd5342-2337-463f-857a-b2c8c3778c6d; Transfers In progress
INFO      2017-06-27 17:40:48  archivematica.mcp.server:jobChainLink:__init__:91:  Running Approve standard transfer (unit 69819795-bee4-4b9d-a36a-e98fd2320a99)
INFO      2017-06-27 17:40:48  archivematica.mcp.server:linkTaskManagerChoice:checkForPreconfiguredXML:122:  Using preconfigured choice None for 0c94e6b5-4714-4bec-82c8-e187e0c04d77
DEBUG     2017-06-27 17:40:54  archivematica.mcp.server.rpcserver:RPCServer:approveJob:54:  Approving: c80ee97b-eb1b-4518-ab32-46ffac1c2380 6953950b-c101-4f4c-a0c3-0cd0684afe5e 1
ERROR     2017-06-27 17:40:54  sqlalchemy.pool.QueuePool:pool:_finalize_fairy:696:  Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 829, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 83, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')`

**Comment by sevein** [comment]
That is useful, @mamedin - thank you!

**Comment by sevein** [comment]
I'd suggest to increase the frequency in which sqlalchemy recycle the connections in the pool. We should also have the channel adapter to retry for longer, perhaps adding exponential backoff or simply more retries.

**Comment by jhsimpson** [comment]
sqlalchemy is being used as a backend by the django-mysqlpool library, which is pip installed by MCPServer.

I think the setting sevein is referring to would be done with http://docs.sqlalchemy.org/en/latest/core/pooling.html#setting-pool-recycle
and I think that is getting set to 119, here: https://github.com/smartfile/django-mysqlpool/blob/master/django_mysqlpool/backends/mysqlpool/base.py#L95

Unless I am mistaken?  If I am correct then I don't think that is the problem.

**Comment by zak-ahmed** [comment]
Please find below the Willow message which needed manual approval : 
{code}{  
   "messageHeader":{  
      "messageId":"30eb3930-7dc6-47db-a8d0-2ab754750484",
      "messageClass":"Event",
      "messageType":"MetadataCreate",
      "messageTimings":{  
         "publishedTimestamp":"2017-10-06T14:12:52+00:00"
      },
      "messageSequence":{  
         "sequence":"a35cc897-3bac-4436-a31f-a8f260b11fef",
         "position":1,
         "total":1
      },
      "version":"0.0.1-SNAPSHOT",
      "messageHistory":[  
         {  
            "machineId":"rdss-institutional-content-based-router",
            "machineAddress":"10.12.169.191",
            "timestamp":"2017-10-06T14:12:53.377113+00:00"
         },
         {  
            "machineId":"rdss-message-broker",
            "machineAddress":"10.11.250.248",
            "timestamp":"2017-10-06T14:12:54.834956+00:00"
         },
         {  
            "machineId":"rdss-institutional-content-based-router",
            "machineAddress":"10.12.169.191",
            "timestamp":"2017-10-06T14:12:55.498562+00:00"
         }
      ]
   },
   "messageBody":{  
      "objectUuid":"0z708w40c",
      "objectTitle":"test 280.1485",
      "objectPersonRole":[  
         {  
            "person":{  
               "personGivenName":"test "
            }
         }
      ],
      "objectDescription":"",
      "objectRights":[  
      ],
      "objectDate":[  
         {  
            "dateValue":"2017-10-06T14:12:53.340197+00:00",
            "dateType":2
         }
      ],
      "objectKeywords":[  
         "test "
      ],
      "objectCategory":[  
      ],
      "objectResourceType":0,
      "objectValue":0,
      "objectIdentifier":[  
         {  
            "identifierValue":"gid://willow/Image/0z708w40c",
            "identifierType":0,
            "relationType":0
         }
      ],
      "objectRelatedIdentifier":[  
      ],
      "objectOrganisationRole":[  
         {  
            "organisation":{  
               "organisationJiscId":280,
               "organisationName":"UNKNOWN",
               "organisationType":0,
               "organisationAddress":"UNKNOWN"
            },
            "role":5
         }
      ],
      "objectPreservationEvent":[  
         {  
            "preservationEventValue":"MetadataCreate",
            "preservationEventType":0,
            "preservationEventDetail":"Image"
         }
      ],
      "objectFile":[  
         {  
            "fileUuid":"nk322d32h",
            "fileIdentifier":"http://willow.dev.280.researchdata.alpha.jisc.ac.uk/downloads/nk322d32h",
            "fileName":"Lorem_ipsum.doc",
            "fileSize":72192,
            "fileChecksum":[  
               {  
                  "checksumType":0,
                  "checksumValue":"f8631d21fac7d846bee54c6d32e2d2f6"
               }
            ],
            "fileCompositionLevel":"UNKNOWN",
            "fileDateModified":[  
               {  
                  "dateValue":"2017-10-06T14:12:53.340257+00:00",
                  "dateType":2
               }
            ],
            "fileUse":0,
            "filePreservationEvent":[  
               {  
                  "preservationEventValue":"UNKNOWN",
                  "preservationEventType":0,
                  "preservationEventDetail":"UNKNOWN"
               }
            ],
            "fileUploadStatus":0,
            "fileStorageStatus":0,
            "fileStorageLocation":"http://willow.dev.280.researchdata.alpha.jisc.ac.uk/downloads/nk322d32h",
            "fileStorageType":2
         }
      ]
   }
}
{code}

**Comment by zak-ahmed** [comment]
Another Willow message: 
```{  
   "messageHeader":{  
      "messageId":"05d062b1-8d9b-4af9-bdf7-e2ba4f973f99",
      "messageClass":"Event",
      "messageType":"MetadataCreate",
      "messageTimings":{  
         "publishedTimestamp":"2017-10-06T13:52:39+00:00"
      },
      "messageSequence":{  
         "sequence":"e60b358b-1b32-407d-918a-9c55e82acda7",
         "position":1,
         "total":1
      },
      "version":"0.0.1-SNAPSHOT",
      "messageHistory":[  
         {  
            "machineId":"rdss-institutional-content-based-router",
            "machineAddress":"10.12.169.191",
            "timestamp":"2017-10-06T13:52:39.496973+00:00"
         },
         {  
            "machineId":"rdss-message-broker",
            "machineAddress":"10.11.250.248",
            "timestamp":"2017-10-06T13:52:41.574152+00:00"
         },
         {  
            "machineId":"rdss-institutional-content-based-router",
            "machineAddress":"10.12.169.191",
            "timestamp":"2017-10-06T13:52:42.237929+00:00"
         }
      ]
   },
   "messageBody":{  
      "objectUuid":"h989r3203",
      "objectTitle":"test 471.1485",
      "objectPersonRole":[  
         {  
            "person":{  
               "personGivenName":"test"
            }
         }
      ],
      "objectDescription":"",
      "objectRights":[  
      ],
      "objectDate":[  
         {  
            "dateValue":"2017-10-06T13:52:39.477693+00:00",
            "dateType":2
         }
      ],
      "objectKeywords":[  
         "test"
      ],
      "objectCategory":[  
      ],
      "objectResourceType":0,
      "objectValue":0,
      "objectIdentifier":[  
         {  
            "identifierValue":"gid://willow/Image/h989r3203",
            "identifierType":0,
            "relationType":0
         }
      ],
      "objectRelatedIdentifier":[  
      ],
      "objectOrganisationRole":[  
         {  
            "organisation":{  
               "organisationJiscId":471,
               "organisationName":"UNKNOWN",
               "organisationType":0,
               "organisationAddress":"UNKNOWN"
            },
            "role":5
         }
      ],
      "objectPreservationEvent":[  
         {  
            "preservationEventValue":"MetadataCreate",
            "preservationEventType":0,
            "preservationEventDetail":"Image"
         }
      ],
      "objectFile":[  
         {  
            "fileUuid":"v692t620b",
            "fileIdentifier":"http://willow.dev.471.researchdata.alpha.jisc.ac.uk/downloads/v692t620b",
            "fileName":"Maecenas_ac_lectus.docx",
            "fileSize":31257,
            "fileChecksum":[  
               {  
                  "checksumType":0,
                  "checksumValue":"21200b1b6af2e77202c4b6f2abc1d483"
               }
            ],
            "fileCompositionLevel":"UNKNOWN",
            "fileDateModified":[  
               {  
                  "dateValue":"2017-10-06T13:52:39.477773+00:00",
                  "dateType":2
               }
            ],
            "fileUse":0,
            "filePreservationEvent":[  
               {  
                  "preservationEventValue":"UNKNOWN",
                  "preservationEventType":0,
                  "preservationEventDetail":"UNKNOWN"
               }
            ],
            "fileUploadStatus":0,
            "fileStorageStatus":0,
            "fileStorageLocation":"http://willow.dev.471.researchdata.alpha.jisc.ac.uk/downloads/v692t620b",
            "fileStorageType":2
         }
      ]
   }
}  ```
