### ISSUE TITLE
Problem: qa branch is not needed

### ISSUE THREAD

**Issue by jhsimpson** [JiscRDSS/rdss-archivematica#48]
The qa branch in this repo is 4 commits behind master currently.  I don't think we need the qa branch, the open pull requests we have now all have master as the target, and I think that is better.  I think the qa branch could be deleted.

@lower29 , @sevein , @mamedin, any objections to deleting the qa branch?

**Comment by sevein** [comment]
:+1:

**Comment by lower29** [comment]
If we no longer need it then yeah I guess it can be deleted. We can always recreate if we need to.

**Comment by jhsimpson** [comment]
I deleted the qa branch.
