### ISSUE TITLE
Problem: Transfers should not be initiated when dataset has no files 

### ISSUE THREAD

**Issue by joel-simpson** [JiscRDSS/rdss-archivematica#59]
Messages received from Willow that did not include any file information were processed by the channel adapter and a new transfer was created. 

A dataset with no files should not trigger preservation. There will be no preservation actions to take. Currently, the attempt at preservation presents at least a couple of problems - the transfer gets called `-1` (or -`2` if a message resulted in a transfer that wasn't approved).  Archivematica then appears to process the transfer, but nothing of value is happening. Because there are no files, the process hangs at the end of Transfer.

I assume that it is valid for a metadata create message to have no references to files (i.e. Willow should be able to create a metadata record for the dataset before the actual files are uploaded). 

We need to clarify the expected behaviour when Archivematica channel adaptor receives a metadata create message with no files.  I see a few options: 
- We could treat this as an error  
- we could ignore the message (with the implicit understanding that a metadata create message with no files is not an instruction to preserve the dataset)
- we could build out the workflow logic for when a dataset should actually be preserved (i.e. something beyond the basic assumption that a metadata create message = preservation request)

**Comment by alanmackenzie** [comment]
FYI @danielgrant 

I think the right behaviour is to ignore the message, metadata only entries are valid given we need to support physical datasets.

Our specification should make the behaviour we expect from preservation systems such as archivematica more explicit, we'll work on this in the coming sprints.

**Comment by mjaddis** [comment]
Corresponding JIRA issue: https://jiscdev.atlassian.net/browse/RDSSARK-234
