### ISSUE TITLE
The ldap docker image has changed from debian 8 to debian 9

### ISSUE THREAD

**Issue by mamedin** [JiscRDSS/rdss-archivematica#60]
Debian 9 uses systemd, so the actual init script is not valid.

Workaround for using the old image:

In  /compose/shib-local/ldap/Dockerfile use: 

`FROM osixia/openldap@sha256:443571790e7db8dd7072d31003089fbec1acf490340173c34a39cd6f4aa345e5`

instead of:

`FROM osixia/openldap`

**Comment by lower29** [comment]
This is now fixed.
