### ISSUE TITLE
virus scanning problem for zips

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-archivematica#73]
If a dataset contains a zip then this fails virus scanning at the 'extract packages' stage of the Transfer workflow.  Virus scanning works for files that are not in a package.

```
Module archivematicaClamscan_v0.0

"80112430-ad7d-4b32-a17c-d57729aa71eb" "/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/OcastaTestVirus2-a522db3b-76d5-4bff-bd1a-f5f81fb6db98/objects/eicar_com.zip-2017-09-19T13_37_59.470212_00_00/eicar.com" "%date%" "%taskUUID%"

Standard streams
Standard error (stderr)

archivematicaClamscan.py: ERROR     2017-09-19 13:38:02,544  archivematica.mcp.client.clamscan:main:100:  File not scanned: /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/OcastaTestVirus2-a522db3b-76d5-4bff-bd1a-f5f81fb6db98/objects/eicar_com.zip-2017-09-19T13_37_59.470212_00_00/eicar.com
```

**Comment by mjaddis** [comment]
Corresponding JIRA issue: https://jiscdev.atlassian.net/browse/RDSSARK-241

**Comment by mjaddis** [comment]
I re-tested this on 480-dev with the new ClamAV container (version 0.2.4) and it seemed to work.

**Comment by helenst** [comment]
@mjaddis I wasn't able to reproduce this on my dev setup either.

**Comment by mjaddis** [comment]
Good, hopefully this is now a non-issue.   Suggest we do quick test on our qa env (as soon as it's ready) and then we can punt this to Jisc for UAT in their env.

**Comment by mamedin** [comment]
I have just tested the TerstVirus TestTransfer (that contains the eicar_com.zip file) in the new qa env and this issue seems fixed.

**Comment by mjaddis** [comment]
I tested with a standard transfer that contains a zip without a virus (original reason this issue was created) in the new qa env and it went through fine as well.  

Now with Jisc for UAT.

**Comment by joel-simpson** [comment]
Jisc have completed UAT successfully and closed defect.
