### ISSUE TITLE
virus scanning for compressed bags

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-archivematica#74]
I transferred a zipped bag into 480-dev and it failed at the virus scanning stage, e.g.:

`archivematicaClamscan.py: ERROR     2017-09-20 10:18:17,621  archivematica.mcp.client.clamscan:main:100:  File not scanned: /var/archivematica/sharedDirectory/currentlyProcessing/YorkZip-0dee5a97-b6c1-4d89-aca7-b0c026b75815/logs/BagIt/bagit.txt`

It is likely that the issue is the same as or related to https://github.com/JiscRDSS/rdss-archivematica/issues/73

**Comment by mjaddis** [comment]
Corresponding JIRA issue: https://jiscdev.atlassian.net/browse/RDSSARK-241

**Comment by helenst** [comment]
@mjaddis Given #73 may now be fixed, is this issue still reproducible?

**Comment by mjaddis** [comment]
I tested a zipped bagit bag Transfer using the QA env and it went through fine.

**Comment by mjaddis** [comment]
Now with Jisc for UAT.

**Comment by joel-simpson** [comment]
Jisc have completed QA and defect is now closed.
