### ISSUE TITLE
Improvement: Use semver for all images

### ISSUE THREAD

**Issue by lower29** [JiscRDSS/rdss-archivematica#88]
There is a requirement for us to use [semantic versioning](https://jiscdev.atlassian.net/wiki/spaces/RDSSAR/pages/135594030/Semantic+Versioning) for all our deployed images so that releases and their dependencies can be tracked and managed.

To start things off, we need to tag the following repositories:
- https://github.com/JiscRDSS/archivematica
- https://github.com/JiscRDSS/archivematica-storage-service
- https://github.com/JiscRDSS/rdss-archivematica-automation-tools
- https://github.com/JiscRDSS/rdss-archivematica-channel-adapter
- https://github.com/JiscRDSS/rdss-arkivum-nextcloud

Issues should be created in each of these repositories to facilitate the addition of the initial semver tags. However, this issue is a good place to coordinate and keep track of these changes as one.

Things to consider:
1. `archivematica` and `archivematica-storage-service` are both forks of upstream Artefactual repositories. The version number should therefore reflect the upstream version.
1. `rdss-archivematica-automation-tools` builds an image for the https://github.com/artefactual/automation-tools repo. This too is an Artefactual repo, but unlike the other two it doesn't have any tags, so we have no existing way of referencing version tags. We can use hashes instead, but the submodule in the `rdss-archivematica-automation-tools` will need updating to reference the specific commit.
1. `rdss-archivematica-channel-adapter` is already using semver tags and is already referenced using these in this repo
1. `rdss-arkivum-nextcloud` builds a Docker image for NextCloud, based on the existing [wonderfall/nextcloud](https://github.com/artefactual/automation-tools) image. There are therefore two versions available to reference here: that of the `wonderfall` image and that of NextCloud. The `wonderfall` repo does not have version tags, so we'd have to reference hashes instead.

Based on this, my recommendation is this:
- `JiscRDSS/archivematica` is initially tagged as `v0.1.0-1.6.1` (where `1.6.1` is the upstream version)
- `JiscRDSS/archivematica-storage-service` is initially tagged as `v0.1.0-0.10.0` (where `0.10.0` is the upstream stable version)
- `JiscRDSS/rdss-archivematica-automation-tools` is initially tagged as `v0.1.0`. We should also raise an issue on the upstream `artefactual/automation-tools` to get that semver tagged - so long as Artefactual agree. If/when the upstream is tagged, then we should change to include this version in the downstream version, e.g. `v0.2.0-x.y.z`.
- `JiscRDSS/rdss-arkivum-nextcloud` is initially tagged as `v0.1.0-12.0.3` (where `12.0.3` is the latest NextCloud version -- or whatever the referenced `wonderfall` version is).

Once this is all done, the image playbooks should be updated and this repo should be initially tagged as `v0.1.0`.

Does this seem a sensible approach? Are there any other suggestions or imrovements on what I've outlined above?

**Comment by lower29** [comment]
@jhsimpson and @sevein, I'd appreciate your feedback on this. And is it reasonable to add semver to the automation tools, or should we manage without?

**Comment by sevein** [comment]
I'm not against including the upstream version but I find it's hard. Would be okay to call `v0.1.0-1.6.1` just `v0.1.0` in certain situations where I can't remember the whole number? And if it we're supporting that idea, would the two be semantically the same in semver?

Do we have other options? I can think of a couple of alternatives.

- Using the build metadata, e.g.: `v0.1.0+uptream.1.6.1` - but it's not a huge improvement.
- Recording the upstream version somewhere else, like in a `.upstream` file inside the repository.

**Comment by jhsimpson** [comment]
The version numbers of archivematica and archivematica-storage-service should not reflect the upstream version.  That is not semver, and that specific question came up last spring and was answered by the jisc core team.  They expect the version numbers to be for the Jisc version, they do not have to match the upstream release version.  

I think it is a reasonable idea to record the upstream version in metadata within the codebase somewhere but I think that is optional.  It is not clear how informative that information would be - the jisc version can and will diverge from the public project, for at least some periods of time, and so fucnctionality described in the official docs may or may not exactly match what is described in the Jisc documentation.

It does point out that the version number displayed in the archivematica dashboard probably needs to be the jisc semver string, not the upstream string.  That is the string that will be recorded in METS files for the premis agent entries.

**Comment by joel-simpson** [comment]
@jhsimpson to support your point above about not recording upstream version in the release tag; Femi from Jisc already commented on this issue in our [wiki page on semver](https://jiscdev.atlassian.net/wiki/spaces/RDSSAR/pages/135594030/Semantic+Versioning). He basically said they didn't care about the upstream version number and wouldn't guarantee they could maintain it properly if we used the numbering scheme I had originally suggested. So makes sense to not do this. 
My suggestion is just to record the upstream version info (whether semver or git commit hash) in release notes when creating the release tag.

**Comment by jhsimpson** [comment]
After discussing internally, I think we have agreed not to put the upstream versions in the semver tags of jisc forks. 

I suggest tagging everything today as v0.1.0.  We can increment each component as PR's are merged, and update rdss-archivematica on Friday with a new release.

An alternative is to use v0.1.0-rc1 for now and remove the release candidate suffix after internal qa testing. Personally I lean towards not tagging at all until after qa testing. I think that would make automating deployments easier - if there is a new tag in rdss-archivematica, do a new deployment to a UAT environment.  

By everything, I mean the repo's @lower29 mentioned:

https://github.com/JiscRDSS/archivematica
https://github.com/JiscRDSS/archivematica-storage-service
https://github.com/JiscRDSS/rdss-archivematica-automation-tools
https://github.com/JiscRDSS/rdss-arkivum-nextcloud

Upstream automation-tools has an rc1 release tag now:
https://github.com/artefactual/automation-tools/releases/tag/v0.1.0-rc1
and associated issue:
https://github.com/artefactual/automation-tools/issues/38
which will be closed when we finalize a 0.1.0 release, in testing for the archivematica 1.7.0 release.

**Comment by lower29** [comment]
Thank you for this @jhsimpson, I will go ahead and tag "everything" with `v.0.1.0-rc1` today - I agree with your reasoning for not using `v0.1.0` straight away. I will hold off tagging `rdss-archivematica` but I will create a PR to update the playbooks with the new tag versions. We can then QA the untagged `rdss-archivematica` after the PR has been merged in, and tag as `v0.1.0-rc1` once it has passed our UAT.

**Comment by lower29** [comment]
We now have the following tagged component versions:

https://github.com/JiscRDSS/archivematica - `v0.1.0-rc.1`
https://github.com/JiscRDSS/archivematica-storage-service - `v0.1.0-rc.1`
https://github.com/JiscRDSS/rdss-arkivum-nextcloud - `v0.1.0-rc.1`
https://github.com/JiscRDSS/rdss-archivematica-msgcreator - `v0.1.0-rc.1`

The change from the proposed `v0.1.0-rc1` to the actual `v0.1.0-rc.1` was in response to a comment from @sevein that `v0.1.0-rc1` is not semver compliant. I've added `rdss-archivematica-msgcreator` to the list because this is part of our QA environment, so should also obeserve this.

Note that the `archivematica` and `archivematica-storage-service` repos both had existing tags inherited from the upstream Artefactual repos at the time the forks were created. These upstream tags have been removed from the JiscRDSS repos, because otherwise the upstream semver tags, e.g. `v1.7.0-rc.1', would be "greater than" the JiscRDSS-originating tags, such as `v0.1.0-rc.1`. This would likely confuse, which is why they have been removed.

I wasn't able to tag `rdss-archivematica-automation-tools` yet because it needs alighning with the upstream `v0.1.0-rc1` first. I have submitted https://github.com/JiscRDSS/rdss-archivematica-automation-tools/pull/9 for this.

**Comment by sevein** [comment]
Looking good. I've just added my :+1: to https://github.com/JiscRDSS/rdss-archivematica/pull/101.

**Comment by lower29** [comment]
Encountered a problem with `rdss-archivematica-automation-tools` in that it won't allow pushes to `master` currently. As per JiscRDSS default, it's configured to require passes from Travis CI before merge, and there isn't a `.travis.yml` defined so Travis CI is just spinning. I'm therefore going to look at adding a very simple configuration for this, or, failing that, changing the repo config to remove this requirement (for now).

**Comment by lower29** [comment]
The Travis CI build is now working nicely for `rdss-archivematica-automation-tools` so I've tagged it as `v0.1.0-rc.1` as planned. This means we're now in good shape for #101, just a bit more testing required now that we have all of the tags in place before I'm ready to merge.

**Comment by lower29** [comment]
All repos have now been tagged and the playbooks have been updated. I think that means that we're ready to do QA on the playbooks ahead of tagging this repo as `v0.1.0-rc.1`, is that right @jhsimpson?

**Comment by jhsimpson** [comment]
@lower29 I created the v0.1.0 tag in this repo, all images are using semver now, closing this issue.
