### ISSUE TITLE
Problem: Microservice List shows exit code but not description

### ISSUE THREAD

**Issue by joel-simpson** [JiscRDSS/rdss-archivematica#91]
Every package (on the Transfer page or Ingest page) has a 'report' like icon beside it where you can navigate to a list of micro-services that have been run.  

Currently, that list is showing exit codes (numbers like '2') rather than the descriptions (like "completed successfully" or "failed"). 

![screen shot 2017-10-24 at 20 10 55](https://user-images.githubusercontent.com/17187309/31974191-156631cc-b8f8-11e7-9b3a-31aa016e3f69.png)

I am seeing this behaviour in our qa-jisc environment as well as 480-dev environment. For reference, this is what this page should look like (from a vanilla install of archivematica 1.6.1): 

![screen shot 2017-10-24 at 18 28 45](https://user-images.githubusercontent.com/17187309/31974211-450aea8a-b8f8-11e7-8b07-296f222cfa75.png)

**Comment by joel-simpson** [comment]
Corresponding Jira issue: https://jiscdev.atlassian.net/browse/RDSSARK-338

**Comment by joel-simpson** [comment]
Tested this on http://augustus.qa.archivematica.org/ (a 1.7.0-rc1 deployment) and the same issue occurs. @sevein you may want to be aware for 1.7.0 release (let me know if you want me to log an issue in artefactual/archivematica repo for this).

**Comment by mjaddis** [comment]
I tested this in the QA env and it appears to work now.
![screen shot 2017-11-09 at 13 59 22 2](https://user-images.githubusercontent.com/25819534/32609089-54681e3e-c556-11e7-9884-24010971d9f7.png)
