### ISSUE TITLE
Improvement: SS staging dir as external volume

### ISSUE THREAD

**Issue by mamedin** [JiscRDSS/rdss-archivematica#94]
For convenience, performance and to better control the space used, the SS staging directory can be mounted as an external volume.

When a transfer starts, the data is initially copied to this directory, so for very large transfers it can be difficult to manage the space on the internal volume of a container, and even more so if several transfers overlap or if temporary data is not being deleted.

Setting this directory as an external volume allows us to place this directory in the most convenient partition during the deployment and a better space management.

This directory is already being used as an external volume in the new QA env. It is mounted on the NFS path `/mnt/nfs/am-ss-staging-data`.

**Comment by sevein** [comment]
Fixed by #95.
